name: influxlp-tools-ci

on:
  pull_request:
  workflow_dispatch:
  
jobs:
  lint:
    uses: ./.github/workflows/lint.yml
    secrets: inherit

  test:
    needs: lint
    uses: ./.github/workflows/test.yml
    secrets: inherit